# Generated by Django 3.2.5 on 2021-09-07 01:28

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_app.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
